<a href="https://colab.research.google.com/github/sureshrapaka/pytorchtutorials/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Basics**

**Tensors**

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.
* Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators
* In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data
*  Tensors are also optimized for automatic differentiation

In [ ]:
import torch
import numpy as np

**Initializing a Tensor**

Tensors can be initialized in various ways
* Tensors can be created directly from data
* Tensors can be created from NumPy arrays and vice versa  
* The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

 ***creatinf tensors  directly from data***

In [ ]:
data = [[2,3],[4,5]]
x_data = torch.tensor(data)

In [ ]:
x_data

tensor([[2, 3],
        [4, 5]])

In [ ]:
print(x_data)

tensor([[2, 3],
        [4, 5]])


In [ ]:
x_data.shape

torch.Size([2, 2])

In [ ]:
x_data.size

<function Tensor.size>

In [ ]:
x_data.size()

torch.Size([2, 2])

***Creating Tensors from Numpy arrays***

In [ ]:
np_data = np.array(data)


In [ ]:
type(np_data)

numpy.ndarray

In [ ]:
x_np = torch.from_numpy(np_data)

In [ ]:
x_np

tensor([[2, 3],
        [4, 5]])

In [ ]:
type(x_np)

torch.Tensor

***Creating a Numpy array from pytorch tensor***

In [ ]:
y_np = x_np.numpy()

In [ ]:
y_np

array([[2, 3],
       [4, 5]])

In [ ]:
type(y_np)

numpy.ndarray

***Creating a tensor from other tensor***

In [ ]:
x_one = torch.ones_like(torch.tensor([[3,4],[4,5]]))

In [ ]:
x_one

tensor([[1, 1],
        [1, 1]])

In [ ]:
data = [[1,2,3],[3,4,5],[4,5,6]]
a = torch.tensor([data])
a

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [ ]:
a.shape

torch.Size([1, 3, 3])

In [ ]:
x_ones = torch.ones_like(a) # retains the properties of a

In [ ]:
x_ones

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [ ]:
x_ones.shape

torch.Size([1, 3, 3])

In [ ]:
x_rand = torch.rand_like(a,dtype=torch.float) # overrides the datatype of a

In [ ]:
x_rand

tensor([[[0.1072, 0.2818, 0.3551],
         [0.6382, 0.2487, 0.3194],
         [0.8269, 0.9576, 0.7794]]])

In [ ]:
shape = (3,4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0334, 0.7876, 0.2214, 0.5031],
        [0.2460, 0.4139, 0.6599, 0.3798],
        [0.6833, 0.3957, 0.7992, 0.6647]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


A***ttributes of a Tensor***

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [ ]:
tns = torch.ones(2,4)
tns

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
print(f"Shape of tensor: {tns.shape}")
print(f"Datatype of tensor: {tns.dtype}")
print(f"Device tensor is stored on: {tns.device}")

Shape of tensor: torch.Size([2, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


***By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method***

In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tns.to('cuda')

In [ ]:
tensor.device

device(type='cuda', index=0)

In [ ]:
tensor.shape

torch.Size([2, 4])

In [ ]:
tensor[0]

tensor([1., 1., 1., 1.], device='cuda:0')

In [ ]:
tensor[1]

tensor([1., 1., 1., 1.], device='cuda:0')

In [ ]:
tensor[:3]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [ ]:
tensor[:4]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [ ]:
tensor[:5]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [ ]:
tensor[0:2,1]

tensor([1., 1.], device='cuda:0')

In [ ]:
tensor[:,3]

tensor([1., 1.], device='cuda:0')

In [ ]:
tensor1 = torch.tensor(shape)

In [ ]:
tensor1

tensor([3, 4])

In [ ]:
tensor2 = torch.tensor([[[1,2,1,3],[2,3,1,3],[2,1,3,1]]],
                       dtype=torch.float,
                       device=torch.device('cuda'))
tensor2

tensor([[[1., 2., 1., 3.],
         [2., 3., 1., 3.],
         [2., 1., 3., 1.]]], device='cuda:0')

In [ ]:
tensor2[:-1]

tensor([], device='cuda:0', size=(0, 3, 4))

In [ ]:
tensor2[:,:3]

tensor([[[1., 2., 1., 3.],
         [2., 3., 1., 3.],
         [2., 1., 3., 1.]]], device='cuda:0')

In [ ]:
tensor2[:,2:3]

tensor([[[2., 1., 3., 1.]]], device='cuda:0')

In [ ]:
tensor2[:2,2:3]


tensor([[[2., 1., 3., 1.]]], device='cuda:0')

In [ ]:
tensor2.shape

torch.Size([1, 3, 4])

In [ ]:
# joining tensors
t_jumbo = torch.cat([tensor2,tensor2,tensor2],dim = 1)

In [ ]:
t_jumbo

tensor([[[1., 2., 1., 3.],
         [2., 3., 1., 3.],
         [2., 1., 3., 1.],
         [1., 2., 1., 3.],
         [2., 3., 1., 3.],
         [2., 1., 3., 1.],
         [1., 2., 1., 3.],
         [2., 3., 1., 3.],
         [2., 1., 3., 1.]]], device='cuda:0')

In [ ]:
t_jumbo.shape

torch.Size([1, 9, 4])

In [ ]:
t_jumbo2 = torch.cat([tensor2,tensor2,tensor2],dim = 2)

In [ ]:
t_jumbo2

tensor([[[1., 2., 1., 3., 1., 2., 1., 3., 1., 2., 1., 3.],
         [2., 3., 1., 3., 2., 3., 1., 3., 2., 3., 1., 3.],
         [2., 1., 3., 1., 2., 1., 3., 1., 2., 1., 3., 1.]]], device='cuda:0')

In [ ]:
t_jumbo2.shape

torch.Size([1, 3, 12])

In [ ]:
y1 = t_jumbo2 * t_jumbo2

In [ ]:
y1

tensor([[[1., 4., 1., 9., 1., 4., 1., 9., 1., 4., 1., 9.],
         [4., 9., 1., 9., 4., 9., 1., 9., 4., 9., 1., 9.],
         [4., 1., 9., 1., 4., 1., 9., 1., 4., 1., 9., 1.]]], device='cuda:0')

In [ ]:
y2 = t_jumbo2.matmul(t_jumbo2.T)
y2

<ipython-input-82-dea9453f5823>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3683.)
  y2 = t_jumbo2.matmul(t_jumbo2.T)


RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [12, 12] but got: [12, 3].

In [ ]:
agg = t_jumbo2.sum()

In [ ]:
agg

tensor(69., device='cuda:0')

In [ ]:
agg = y1.sum()

In [ ]:
agg

tensor(159., device='cuda:0')

In [ ]:
agg_item = agg.item()
agg_item

159.0

In [ ]:
type(agg_item)

float